name: transformers-cpu
channels:
  - huggingface
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pytorch=2.1.2
  - torchvision=0.16
  - torchaudio=2.1.2
  - cpuonly=2.0
  - transformers=4.22
  - pandas=2.1
